
INSERT INTO users (id, username, email, password_hash) VALUES
  (6, 'alicia', 'alicia@example.com', 'hashedpassword1'),
  (7, 'caroline', 'caroline@example.com', 'hashedpassword2'),
  (8, 'bird', 'bird@example.com', 'hashedpassword3'),
  (9, 'dad', 'dad@example.com', 'hashedpassword4'),
  (10, 'vera', 'vera@example.com', 'hashedpassword5');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 1, 'Review by user 1 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 1, 'Review by user 2 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 1, 'Review by user 3 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 1, 'Review by user 4 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 1, 'Review by user 5 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 1, 'Review by user 6 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 1, 'Review by user 7 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 1, 'Review by user 8 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 1, 'Review by user 9 on item 1.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 2, 'Review by user 3 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 2, 'Review by user 4 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 2, 'Review by user 5 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 2, 'Review by user 6 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 2, 'Review by user 7 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 2, 'Review by user 8 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 2, 'Review by user 9 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 2, 'Review by user 10 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 2, 'Review by user 1 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 2, 'Review by user 2 on item 2.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 3, 'Review by user 4 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 3, 'Review by user 5 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 3, 'Review by user 6 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 3, 'Review by user 7 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 3, 'Review by user 8 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 3, 'Review by user 9 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 3, 'Review by user 10 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 3, 'Review by user 1 on item 3.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 4, 'Review by user 5 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 4, 'Review by user 6 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 4, 'Review by user 7 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 4, 'Review by user 8 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 4, 'Review by user 9 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 4, 'Review by user 10 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 4, 'Review by user 1 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 4, 'Review by user 2 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 4, 'Review by user 3 on item 4.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 5, 'Review by user 6 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 5, 'Review by user 7 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 5, 'Review by user 8 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 5, 'Review by user 9 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 5, 'Review by user 10 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 5, 'Review by user 1 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 5, 'Review by user 2 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 5, 'Review by user 3 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 5, 'Review by user 4 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 5, 'Review by user 5 on item 5.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 6, 'Review by user 7 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 6, 'Review by user 8 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 6, 'Review by user 9 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 6, 'Review by user 10 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 6, 'Review by user 1 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 6, 'Review by user 2 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 6, 'Review by user 3 on item 6.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 7, 'Review by user 8 on item 7.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 7, 'Review by user 9 on item 7.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 7, 'Review by user 10 on item 7.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 7, 'Review by user 1 on item 7.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 7, 'Review by user 2 on item 7.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 7, 'Review by user 3 on item 7.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 8, 'Review by user 9 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 8, 'Review by user 10 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 8, 'Review by user 1 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 8, 'Review by user 2 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 8, 'Review by user 3 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 8, 'Review by user 4 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 8, 'Review by user 5 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 8, 'Review by user 6 on item 8.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 9, 'Review by user 10 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 9, 'Review by user 1 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 9, 'Review by user 2 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 9, 'Review by user 3 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 9, 'Review by user 4 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 9, 'Review by user 5 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 9, 'Review by user 6 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 9, 'Review by user 7 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 9, 'Review by user 8 on item 9.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 10, 'Review by user 1 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 10, 'Review by user 2 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 10, 'Review by user 3 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 10, 'Review by user 4 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 10, 'Review by user 5 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 10, 'Review by user 6 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 10, 'Review by user 7 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 10, 'Review by user 8 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 10, 'Review by user 9 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 10, 'Review by user 10 on item 10.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 11, 'Review by user 2 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 11, 'Review by user 3 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 11, 'Review by user 4 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 11, 'Review by user 5 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 11, 'Review by user 6 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 11, 'Review by user 7 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 11, 'Review by user 8 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 11, 'Review by user 9 on item 11.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 12, 'Review by user 3 on item 12.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 12, 'Review by user 4 on item 12.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 12, 'Review by user 5 on item 12.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 12, 'Review by user 6 on item 12.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 12, 'Review by user 7 on item 12.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 12, 'Review by user 8 on item 12.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 13, 'Review by user 4 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 13, 'Review by user 5 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 13, 'Review by user 6 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 13, 'Review by user 7 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 13, 'Review by user 8 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 13, 'Review by user 9 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 13, 'Review by user 10 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 13, 'Review by user 1 on item 13.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 14, 'Review by user 5 on item 14.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 14, 'Review by user 6 on item 14.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 14, 'Review by user 7 on item 14.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 14, 'Review by user 8 on item 14.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 14, 'Review by user 9 on item 14.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 14, 'Review by user 10 on item 14.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 15, 'Review by user 6 on item 15.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 15, 'Review by user 7 on item 15.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 15, 'Review by user 8 on item 15.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 15, 'Review by user 9 on item 15.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 15, 'Review by user 10 on item 15.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 15, 'Review by user 1 on item 15.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 16, 'Review by user 7 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 16, 'Review by user 8 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 16, 'Review by user 9 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 16, 'Review by user 10 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 16, 'Review by user 1 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 16, 'Review by user 2 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 16, 'Review by user 3 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 16, 'Review by user 4 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 16, 'Review by user 5 on item 16.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 17, 'Review by user 8 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 17, 'Review by user 9 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 17, 'Review by user 10 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 17, 'Review by user 1 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 17, 'Review by user 2 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 17, 'Review by user 3 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 17, 'Review by user 4 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 17, 'Review by user 5 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 17, 'Review by user 6 on item 17.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 18, 'Review by user 9 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 18, 'Review by user 10 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 18, 'Review by user 1 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 18, 'Review by user 2 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 18, 'Review by user 3 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 18, 'Review by user 4 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 18, 'Review by user 5 on item 18.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 19, 'Review by user 10 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 19, 'Review by user 1 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 19, 'Review by user 2 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 19, 'Review by user 3 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 19, 'Review by user 4 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 19, 'Review by user 5 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 19, 'Review by user 6 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 19, 'Review by user 7 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 19, 'Review by user 8 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 19, 'Review by user 9 on item 19.');
INSERT INTO reviews (user_id, item_id, text) VALUES (1, 20, 'Review by user 1 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 20, 'Review by user 2 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 20, 'Review by user 3 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 20, 'Review by user 4 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 20, 'Review by user 5 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 20, 'Review by user 6 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 20, 'Review by user 7 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 20, 'Review by user 8 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 20, 'Review by user 9 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 20, 'Review by user 10 on item 20.');
INSERT INTO reviews (user_id, item_id, text) VALUES (2, 21, 'Review by user 2 on item 21.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 21, 'Review by user 3 on item 21.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 21, 'Review by user 4 on item 21.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 21, 'Review by user 5 on item 21.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 21, 'Review by user 6 on item 21.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 21, 'Review by user 7 on item 21.');
INSERT INTO reviews (user_id, item_id, text) VALUES (3, 22, 'Review by user 3 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 22, 'Review by user 4 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 22, 'Review by user 5 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 22, 'Review by user 6 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 22, 'Review by user 7 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 22, 'Review by user 8 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 22, 'Review by user 9 on item 22.');
INSERT INTO reviews (user_id, item_id, text) VALUES (4, 23, 'Review by user 4 on item 23.');
INSERT INTO reviews (user_id, item_id, text) VALUES (5, 23, 'Review by user 5 on item 23.');
INSERT INTO reviews (user_id, item_id, text) VALUES (6, 23, 'Review by user 6 on item 23.');
INSERT INTO reviews (user_id, item_id, text) VALUES (7, 23, 'Review by user 7 on item 23.');
INSERT INTO reviews (user_id, item_id, text) VALUES (8, 23, 'Review by user 8 on item 23.');
INSERT INTO reviews (user_id, item_id, text) VALUES (9, 23, 'Review by user 9 on item 23.');
INSERT INTO reviews (user_id, item_id, text) VALUES (10, 23, 'Review by user 10 on item 23.');
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (1, 'Performance', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (1, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (1, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (1, 'Value for Money', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (2, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (2, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (2, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (2, 'Value for Money', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (3, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (3, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (3, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (3, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (4, 'Performance', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (4, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (4, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (4, 'Value for Money', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (5, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (5, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (5, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (5, 'Value for Money', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (6, 'Performance', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (6, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (6, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (6, 'Value for Money', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (7, 'Performance', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (7, 'Battery Life', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (7, 'Design', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (7, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (8, 'Performance', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (8, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (8, 'Design', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (8, 'Value for Money', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (9, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (9, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (9, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (9, 'Value for Money', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (10, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (10, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (10, 'Design', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (10, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (11, 'Performance', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (11, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (11, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (11, 'Value for Money', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (12, 'Performance', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (12, 'Battery Life', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (12, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (12, 'Value for Money', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (13, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (13, 'Battery Life', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (13, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (13, 'Value for Money', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (14, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (14, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (14, 'Design', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (14, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (15, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (15, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (15, 'Design', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (15, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (16, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (16, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (16, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (16, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (17, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (17, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (17, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (17, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (18, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (18, 'Battery Life', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (18, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (18, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (19, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (19, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (19, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (19, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (20, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (20, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (20, 'Design', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (20, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (21, 'Performance', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (21, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (21, 'Design', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (21, 'Value for Money', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (22, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (22, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (22, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (22, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (23, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (23, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (23, 'Design', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (23, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (24, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (24, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (24, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (24, 'Value for Money', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (25, 'Performance', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (25, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (25, 'Design', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (25, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (26, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (26, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (26, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (26, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (27, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (27, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (27, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (27, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (28, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (28, 'Battery Life', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (28, 'Design', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (28, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (29, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (29, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (29, 'Design', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (29, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (30, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (30, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (30, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (30, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (31, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (31, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (31, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (31, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (32, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (32, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (32, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (32, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (33, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (33, 'Battery Life', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (33, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (33, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (34, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (34, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (34, 'Design', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (34, 'Value for Money', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (35, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (35, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (35, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (35, 'Value for Money', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (36, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (36, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (36, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (36, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (37, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (37, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (37, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (37, 'Value for Money', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (38, 'Performance', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (38, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (38, 'Design', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (38, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (39, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (39, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (39, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (39, 'Value for Money', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (40, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (40, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (40, 'Design', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (40, 'Value for Money', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (41, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (41, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (41, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (41, 'Value for Money', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (42, 'Performance', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (42, 'Battery Life', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (42, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (42, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (43, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (43, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (43, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (43, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (44, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (44, 'Battery Life', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (44, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (44, 'Value for Money', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (45, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (45, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (45, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (45, 'Value for Money', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (46, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (46, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (46, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (46, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (47, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (47, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (47, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (47, 'Value for Money', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (48, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (48, 'Battery Life', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (48, 'Design', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (48, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (49, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (49, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (49, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (49, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (50, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (50, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (50, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (50, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (51, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (51, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (51, 'Design', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (51, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (52, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (52, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (52, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (52, 'Value for Money', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (53, 'Performance', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (53, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (53, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (53, 'Value for Money', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (54, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (54, 'Battery Life', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (54, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (54, 'Value for Money', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (55, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (55, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (55, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (55, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (56, 'Performance', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (56, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (56, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (56, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (57, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (57, 'Battery Life', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (57, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (57, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (58, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (58, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (58, 'Design', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (58, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (59, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (59, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (59, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (59, 'Value for Money', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (60, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (60, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (60, 'Design', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (60, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (61, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (61, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (61, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (61, 'Value for Money', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (62, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (62, 'Battery Life', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (62, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (62, 'Value for Money', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (63, 'Performance', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (63, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (63, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (63, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (64, 'Performance', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (64, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (64, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (64, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (65, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (65, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (65, 'Design', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (65, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (66, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (66, 'Battery Life', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (66, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (66, 'Value for Money', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (67, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (67, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (67, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (67, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (68, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (68, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (68, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (68, 'Value for Money', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (69, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (69, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (69, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (69, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (70, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (70, 'Battery Life', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (70, 'Design', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (70, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (71, 'Performance', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (71, 'Battery Life', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (71, 'Design', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (71, 'Value for Money', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (72, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (72, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (72, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (72, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (73, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (73, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (73, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (73, 'Value for Money', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (74, 'Performance', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (74, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (74, 'Design', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (74, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (75, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (75, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (75, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (75, 'Value for Money', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (76, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (76, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (76, 'Design', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (76, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (77, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (77, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (77, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (77, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (78, 'Performance', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (78, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (78, 'Design', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (78, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (79, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (79, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (79, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (79, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (80, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (80, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (80, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (80, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (81, 'Performance', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (81, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (81, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (81, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (82, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (82, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (82, 'Design', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (82, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (83, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (83, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (83, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (83, 'Value for Money', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (84, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (84, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (84, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (84, 'Value for Money', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (85, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (85, 'Battery Life', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (85, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (85, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (86, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (86, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (86, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (86, 'Value for Money', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (87, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (87, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (87, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (87, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (88, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (88, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (88, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (88, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (89, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (89, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (89, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (89, 'Value for Money', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (90, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (90, 'Battery Life', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (90, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (90, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (91, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (91, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (91, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (91, 'Value for Money', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (92, 'Performance', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (92, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (92, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (92, 'Value for Money', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (93, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (93, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (93, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (93, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (94, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (94, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (94, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (94, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (95, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (95, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (95, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (95, 'Value for Money', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (96, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (96, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (96, 'Design', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (96, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (97, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (97, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (97, 'Design', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (97, 'Value for Money', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (98, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (98, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (98, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (98, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (99, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (99, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (99, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (99, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (100, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (100, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (100, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (100, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (101, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (101, 'Battery Life', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (101, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (101, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (102, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (102, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (102, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (102, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (103, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (103, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (103, 'Design', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (103, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (104, 'Performance', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (104, 'Battery Life', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (104, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (104, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (105, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (105, 'Battery Life', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (105, 'Design', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (105, 'Value for Money', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (106, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (106, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (106, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (106, 'Value for Money', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (107, 'Performance', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (107, 'Battery Life', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (107, 'Design', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (107, 'Value for Money', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (108, 'Performance', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (108, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (108, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (108, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (109, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (109, 'Battery Life', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (109, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (109, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (110, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (110, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (110, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (110, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (111, 'Performance', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (111, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (111, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (111, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (112, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (112, 'Battery Life', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (112, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (112, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (113, 'Performance', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (113, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (113, 'Design', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (113, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (114, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (114, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (114, 'Design', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (114, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (115, 'Performance', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (115, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (115, 'Design', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (115, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (116, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (116, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (116, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (116, 'Value for Money', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (117, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (117, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (117, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (117, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (118, 'Performance', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (118, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (118, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (118, 'Value for Money', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (119, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (119, 'Battery Life', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (119, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (119, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (120, 'Performance', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (120, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (120, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (120, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (121, 'Performance', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (121, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (121, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (121, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (122, 'Performance', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (122, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (122, 'Design', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (122, 'Value for Money', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (123, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (123, 'Battery Life', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (123, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (123, 'Value for Money', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (124, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (124, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (124, 'Design', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (124, 'Value for Money', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (125, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (125, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (125, 'Design', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (125, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (126, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (126, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (126, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (126, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (127, 'Performance', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (127, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (127, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (127, 'Value for Money', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (128, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (128, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (128, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (128, 'Value for Money', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (129, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (129, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (129, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (129, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (130, 'Performance', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (130, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (130, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (130, 'Value for Money', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (131, 'Performance', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (131, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (131, 'Design', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (131, 'Value for Money', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (132, 'Performance', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (132, 'Battery Life', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (132, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (132, 'Value for Money', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (133, 'Performance', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (133, 'Battery Life', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (133, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (133, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (134, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (134, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (134, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (134, 'Value for Money', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (135, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (135, 'Battery Life', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (135, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (135, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (136, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (136, 'Battery Life', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (136, 'Design', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (136, 'Value for Money', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (137, 'Performance', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (137, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (137, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (137, 'Value for Money', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (138, 'Performance', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (138, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (138, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (138, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (139, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (139, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (139, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (139, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (140, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (140, 'Battery Life', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (140, 'Design', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (140, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (141, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (141, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (141, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (141, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (142, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (142, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (142, 'Design', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (142, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (143, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (143, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (143, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (143, 'Value for Money', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (144, 'Performance', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (144, 'Battery Life', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (144, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (144, 'Value for Money', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (145, 'Performance', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (145, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (145, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (145, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (146, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (146, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (146, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (146, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (147, 'Performance', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (147, 'Battery Life', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (147, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (147, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (148, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (148, 'Battery Life', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (148, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (148, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (149, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (149, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (149, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (149, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (150, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (150, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (150, 'Design', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (150, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (151, 'Performance', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (151, 'Battery Life', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (151, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (151, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (152, 'Performance', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (152, 'Battery Life', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (152, 'Design', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (152, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (153, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (153, 'Battery Life', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (153, 'Design', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (153, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (154, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (154, 'Battery Life', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (154, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (154, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (155, 'Performance', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (155, 'Battery Life', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (155, 'Design', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (155, 'Value for Money', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (156, 'Performance', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (156, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (156, 'Design', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (156, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (157, 'Performance', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (157, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (157, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (157, 'Value for Money', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (158, 'Performance', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (158, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (158, 'Design', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (158, 'Value for Money', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (159, 'Performance', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (159, 'Battery Life', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (159, 'Design', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (159, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (160, 'Performance', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (160, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (160, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (160, 'Value for Money', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (161, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (161, 'Battery Life', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (161, 'Design', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (161, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (162, 'Performance', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (162, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (162, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (162, 'Value for Money', 3.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (163, 'Performance', 4.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (163, 'Battery Life', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (163, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (163, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (164, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (164, 'Battery Life', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (164, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (164, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (165, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (165, 'Battery Life', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (165, 'Design', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (165, 'Value for Money', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (166, 'Performance', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (166, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (166, 'Design', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (166, 'Value for Money', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (167, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (167, 'Battery Life', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (167, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (167, 'Value for Money', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (168, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (168, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (168, 'Design', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (168, 'Value for Money', 2.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (169, 'Performance', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (169, 'Battery Life', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (169, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (169, 'Value for Money', 4.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (170, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (170, 'Battery Life', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (170, 'Design', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (170, 'Value for Money', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (171, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (171, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (171, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (171, 'Value for Money', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (172, 'Performance', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (172, 'Battery Life', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (172, 'Design', 3.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (172, 'Value for Money', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (173, 'Performance', 3.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (173, 'Battery Life', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (173, 'Design', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (173, 'Value for Money', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (174, 'Performance', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (174, 'Battery Life', 3.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (174, 'Design', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (174, 'Value for Money', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (175, 'Performance', 4.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (175, 'Battery Life', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (175, 'Design', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (175, 'Value for Money', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (176, 'Performance', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (176, 'Battery Life', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (176, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (176, 'Value for Money', 5.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (177, 'Performance', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (177, 'Battery Life', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (177, 'Design', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (177, 'Value for Money', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (178, 'Performance', 4.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (178, 'Battery Life', 2.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (178, 'Design', 4.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (178, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (179, 'Performance', 4.3);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (179, 'Battery Life', 3.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (179, 'Design', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (179, 'Value for Money', 3.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (180, 'Performance', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (180, 'Battery Life', 2.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (180, 'Design', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (180, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (181, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (181, 'Battery Life', 3.5);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (181, 'Design', 3.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (181, 'Value for Money', 3.8);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (182, 'Performance', 4.1);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (182, 'Battery Life', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (182, 'Design', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (182, 'Value for Money', 4.7);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (183, 'Performance', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (183, 'Battery Life', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (183, 'Design', 3.0);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (183, 'Value for Money', 2.9);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (184, 'Performance', 2.6);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (184, 'Battery Life', 4.2);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (184, 'Design', 4.4);
INSERT INTO review_metrics (review_id, metric_name, value) VALUES (184, 'Value for Money', 4.1);